services:
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - '3309:3306'
    volumes:
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    networks:
      - backend
  nest:
    image: node:20-buster
    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=${TZ}
      - MYSQL_PORT=${DB_PORT}
      - CHOKIDAR_USEPOLLING=true
      - REDIS_URL=${REDIS_URL}
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./nest:/app
    working_dir: /app
    command: bash -c "npm install && npm run start:dev"
    networks:
      - backend
    depends_on:
      - db    
  frontend:
    image: nginx:1.25.2
    ports:
      - '5173:80'
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - nest
  redis:
    image: redis:7.4.1
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - backend
networks:
  backend:


volumes:
  mysqldata: